### ISSUE TITLE
After uninstalling the mod, the size of the mecha combustion chamber is abnormal.

### ISSUE THREAD

**Issue by ArgonCrystal** [appuns/DSPBigMechaStorage#1]
After uninstalling the mod, the size of the mecha combustion chamber is abnormal.
modをアンインストールした後、メカ燃焼室のサイズが異常です。
Here is the screenshot link
これがスクリーンショットのリンクです
![This is an image](https://github.com/ArgonCrystal/bug-jpg/blob/main/bug%201.png)
mod mod version 1.0.3

**Comment by appuns** [comment]
Added ability to reset to new version.
